name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    strategy:
      matrix:
        ROS_DISTRO: [iron]
        ROS_REPO: [testing, main]
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: # either pass all entries explicitly
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
