name: Run MoveIt Middleware Benchmarks

on: [push, pull_request, workflow_dispatch]

jobs:
  run_middleware_benchmarks:
    name: run_benchmarks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cihataltiparmak/dummy_ci:latest
    steps:
      - name: run perception benchmark
        run: |
          pwd
          ls ..
          ls /
          ls /ws
          cd /ws/src/moveit_middleware_benchmark
          git pull
          cd /ws
          colcon build --mixin release --packages-select moveit_middleware_benchmark
          cd /ws
          . /opt/ros/rolling/setup.sh
          . install/setup.sh
          ros2 launch moveit_middleware_benchmark scenario_perception_pipeline_benchmark.launch.py
          
    
