name: Run MoveIt Middleware Benchmarks

on: [push, pull_request, workflow_dispatch]

jobs:
  run_middleware_benchmarks:
    name: run_benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    container:
      image: ghcr.io/cihataltiparmak/dummy_ci:latest
    steps:
      - name: run perception benchmark
        run: |
          pwd
          ls ..
          ls /
          ls /ws
          cd /ws/src/moveit_middleware_benchmark
          git pull
          cd /ws
          . /opt/ros/rolling/setup.sh
          . install/setup.sh
          colcon build --packages-select moveit_middleware_benchmark
          cd /ws
          . install/setup.sh
          ros2 launch moveit_middleware_benchmark scenario_perception_pipeline_benchmark.launch.py
          mv /ws/middleware_benchmark_results.json /ws/middleware_benchmark_results_1.json
          ros2 launch moveit_middleware_benchmark scenario_perception_pipeline_benchmark.launch.py
          mv /ws/middleware_benchmark_results.json /ws/middleware_benchmark_results_2.json
      - name: clone repo
        uses: actions/checkout@v3
      - name: add to safe directory
        run: |
          git config --global --add safe.directory /__w/dummy_ci/dummy_ci
      - name: push perception benchmark results to github pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Dummy Project Perception Pipeline Benchmark 1
          tool: 'googlecpp'
          output-file-path: /ws/middleware_benchmark_results_1.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "elmaciyim_elmaci/benchmarks"
      - name: push perception benchmark results to github pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Dummy Project Perception Pipeline Benchmark 2
          tool: 'googlecpp'
          output-file-path: /ws/middleware_benchmark_results_2.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "elmaciyim_elmaci/benchmarks" 
          
    
