name: Run MoveIt Middleware Benchmarks

on: [push, pull_request, workflow_dispatch]

jobs:
  run_middleware_benchmarks:
    name: run_benchmarks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cihataltiparmak/dummy_ci:latest
    steps:
      - name: run perception benchmark
        run: |
          pwd
          ls ..
          ls /
          ls /ws
          cd /ws/src/moveit_middleware_benchmark
          git pull
          cd /ws
          . /opt/ros/rolling/setup.sh
          . install/setup.sh
          colcon build --packages-select moveit_middleware_benchmark
          cd /ws
          . install/setup.sh
          ros2 launch moveit_middleware_benchmark scenario_perception_pipeline_benchmark.launch.py
      - name: clone repo
        uses: actions/checkout@v3
      - name: push perception benchmark results to github pages
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Dummy Project Perception Pipeline Benchmark
          tool: 'googlecpp'
          output-file-path: /ws/middleware_benchmark_results.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          gh-pages-branch: "gh-pages"
          
    
