name: MoveIt Middleware Benchmark Github Action Test

on: [push, pull_request, workflow_dispatch]

jobs:
  moveit_middleware_benchmark_github_action_test:
    name: build
    runs-on: ubuntu-latest
    container: 
      image: ./
    steps:
      - name: run_ros_source
        run: source /opt/ros/rolling/setup.bash
      - name: run_percpetion_pipeline_benchmark
        run: |
          source /opt/ros/rolling/setup.bash
          cd ws
          source install/setup.bash
          ros2 launch moveit_middleware_benchmark scenario_perception_pipeline_benchmark.launch.py
        
