name: MoveIt Middleware Benchmark Github Action Test

on: [push, pull_request, workflow_dispatch]

jobs:
  moveit_middleware_benchmark_github_action_test:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/CihatAltiparmak/dummy_ci
          flavor: latest=true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  run_middleware_benchmarks:
    name: run_benchmarks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cihataltiparmak/dummy_ci:latest
    steps:
      - name: run perception benchmark
        run: |
          cd ws
          source /opt/ros/rolling/setup.bash
          source install/setup.bash
          ros2 launch moveit_middleware_benchmark scenario_perception_pipeline_benchmark.launch.py
          
    
